"""PDF reports (BUILD-PLAN M7). Offline: EARTH_IMPL=stub."""

from __future__ import annotations

import json
import re
import shutil
from collections.abc import Iterator
from pathlib import Path

import pytest
from fastapi import FastAPI
from fastapi.testclient import TestClient

from app.api.routes import layers, reports, runs, shares
from app.schemas.stream import ClarificationNeeded, ClarificationQuestion, ValueSource
from app.services import report as report_service
from app.services import runs as run_store

ALICE = {"X-User-Id": "alice"}
BOB = {"X-User-Id": "bob"}
SECRET = "SECRET-MEMORY-TEXT-fish-farm-owner"


@pytest.fixture
def client(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> Iterator[TestClient]:
    monkeypatch.setenv("EARTH_IMPL", "stub")
    monkeypatch.setenv("EARTH_DATA_DIR", str(tmp_path / "data"))
    monkeypatch.setenv("RUNS_DB_PATH", str(tmp_path / "runs.sqlite"))
    app = FastAPI()
    for mod in (runs, layers, shares, reports):
        app.include_router(mod.router, prefix="/api")
    with TestClient(app) as c:
        yield c


def _make_run(client: TestClient, headers: dict[str, str] = ALICE) -> str:
    res = client.post(
        "/api/runs", json={"question": "Have these ponds been filled in?"}, headers=headers
    )
    assert res.status_code == 200
    for chunk in res.text.replace("\r\n", "\n").split("\n\n"):
        if "run_started" in chunk:
            line = next(x for x in chunk.split("\n") if x.startswith("data:"))
            return json.loads(line[5:])["run_id"]
    raise AssertionError("no run_started")


def _pages(pdf: bytes) -> int:
    return len(re.findall(rb"/Type /Page\b(?!s)", pdf))


def test_owner_downloads_pdf(client: TestClient) -> None:
    run_id = _make_run(client)
    res = client.get(f"/api/runs/{run_id}/report.pdf", headers=ALICE)
    assert res.status_code == 200
    assert res.headers["content-type"] == "application/pdf"
    assert res.headers["content-disposition"] == (
        f'attachment; filename="earth-agent-{run_id}.pdf"'
    )
    assert res.content.startswith(b"%PDF") and res.content.rstrip().endswith(b"%%EOF")
    assert _pages(res.content) >= 1


def test_not_owner_and_unknown(client: TestClient) -> None:
    run_id = _make_run(client)
    assert client.get(f"/api/runs/{run_id}/report.pdf", headers=BOB).status_code == 404
    assert client.get(f"/api/runs/{run_id}/report.pdf").status_code == 404  # "demo"
    assert client.get("/api/runs/r_nope/report.pdf", headers=ALICE).status_code == 404
    assert client.get("/api/runs/BAD!/report.pdf", headers=ALICE).status_code == 400


def test_unfinished_run_is_409(client: TestClient) -> None:
    run_id = _make_run(client)
    run_store.update_status(run_id, "waiting_user")
    assert client.get(f"/api/runs/{run_id}/report.pdf", headers=ALICE).status_code == 409


def test_share_download_and_revoke(client: TestClient) -> None:
    run_id = _make_run(client)
    slug = client.post(f"/api/runs/{run_id}/share", headers=ALICE).json()["slug"]
    res = client.get(f"/api/shares/{slug}/report.pdf")  # public
    assert res.status_code == 200 and res.content.startswith(b"%PDF")
    assert (
        res.headers["content-disposition"] == f'attachment; filename="earth-agent-{slug[:8]}.pdf"'
    )
    assert run_id.encode() not in res.content
    assert client.get("/api/shares/nope/report.pdf").status_code == 404
    assert client.delete(f"/api/shares/{slug}", headers=ALICE).status_code == 204
    assert client.get(f"/api/shares/{slug}/report.pdf").status_code == 410


def test_pdf_has_the_content(client: TestClient, monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setattr(report_service, "PAGE_COMPRESSION", 0)
    run_id = _make_run(client)
    run = run_store.get_run(run_id)
    assert run is not None and run.answer is not None
    pdf = client.get(f"/api/runs/{run_id}/report.pdf", headers=ALICE).content
    for text in (
        b"Have these ponds been filled in?",
        run.answer.sentence.encode("latin-1", "replace")[:30],
        b"Confidence:",
        b"Provenance",
        b"Generated by Earth Agent",
    ):
        assert text in pdf, text


def test_missing_images_become_placeholders(client: TestClient, tmp_path: Path) -> None:
    run_id = _make_run(client)
    shutil.rmtree(tmp_path / "data" / "layers", ignore_errors=True)
    res = client.get(f"/api/runs/{run_id}/report.pdf", headers=ALICE)
    assert res.status_code == 200 and res.content.startswith(b"%PDF")


def test_non_latin_text_does_not_break(client: TestClient) -> None:
    run_id = _make_run(client)
    run = run_store.get_run(run_id)
    assert run is not None and run.answer is not None
    run.lang = "zh-Hant"
    run.question = "池塘有被填平嗎? <b>&"
    run.answer.sentence = "魚塘 <unclosed"
    run_store.save_run(run)
    res = client.get(f"/api/runs/{run_id}/report.pdf", headers=ALICE)
    assert res.status_code == 200 and res.content.startswith(b"%PDF")


def test_planted_secret_is_not_in_the_pdf(
    client: TestClient, monkeypatch: pytest.MonkeyPatch
) -> None:
    monkeypatch.setattr(report_service, "PAGE_COMPRESSION", 0)
    run_id = _make_run(client)
    run = run_store.get_run(run_id)
    assert run is not None
    run.params = {"answers": {"crop": SECRET}, "note": SECRET}
    run.script = f"def run(**p):\n    return {{'x': '{SECRET}'}}\n"
    run.events.append(
        ClarificationNeeded(
            questions=[
                ClarificationQuestion(
                    key="crop",
                    label="Crop?",
                    options=[],
                    value=SECRET,
                    source=ValueSource(**{"from": "memory"}, saved="2026-09-12"),
                )
            ],
            remember=True,
        )
    )
    run_store.save_run(run)
    slug = client.post(f"/api/runs/{run_id}/share", headers=ALICE).json()["slug"]
    pdfs = [
        client.get(f"/api/runs/{run_id}/report.pdf", headers=ALICE).content,
        client.get(f"/api/shares/{slug}/report.pdf").content,
    ]
    for pdf in pdfs:
        assert b"Have these ponds" in pdf  # text is searchable, so the check below means something
        assert SECRET.encode() not in pdf
        for private in (b"alice", run.thread_id.encode(), b"def run("):
            assert private not in pdf, private
