"""PDF report for a run (BUILD-PLAN M7), drawn with reportlab (pure Python, no system libraries).

The report is built from a `SharedRun` snapshot (`app.services.shares.snapshot`), so it holds
exactly what a share link holds and never params, events, script, memory, user or thread id.
Images are read from the layer PNGs on disk; a missing file becomes a grey placeholder box.

Limitation: the built-in Helvetica font is Latin-1 only. Other characters (e.g. Chinese in a
`zh-Hant` run) are printed as "?".
"""

from __future__ import annotations

import io
import re
from datetime import date, datetime
from pathlib import Path
from typing import Any
from xml.sax.saxutils import escape

from reportlab.graphics.shapes import Circle, Drawing, Line, PolyLine, Rect, String
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.lib.utils import ImageReader
from reportlab.platypus import (
    Flowable,
    Image,
    KeepTogether,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

from app.schemas.shares import SharedRun
from earth import settings as earth_settings
from earth.blocks import (
    HighlightBlock,
    HypothesesBlock,
    LimitsBlock,
    SceneStripBlock,
    StatBlock,
    ThenNowBlock,
    TimelineBlock,
)
from earth.blocks import Image as BlockImage
from earth.render import layer_path

__all__ = ["PAGE_COMPRESSION", "render_report"]

#: 1 = compressed page streams (default). Tests set 0 to search the PDF bytes for text.
PAGE_COMPRESSION = 1

FOOTER = "Generated by Constellation from free satellite data - not an official assessment"
_WIDTH = A4[0] - 40 * mm  # usable width
_INK = colors.HexColor("#1f2937")
_MUTED = colors.HexColor("#6b7280")
_ACCENT = colors.HexColor("#0f766e")
_RED = colors.HexColor("#dc2626")
_LINE = colors.HexColor("#d1d5db")
_URL_RE = re.compile(r"/layers/(?:[^/]+/)?([a-z0-9_]+)/([^/]+)\.png$")

_ss = getSampleStyleSheet()
_BODY = ParagraphStyle("body", parent=_ss["BodyText"], fontSize=10, leading=14, textColor=_INK)
_SMALL = ParagraphStyle("small", parent=_BODY, fontSize=8, leading=10.5, textColor=_MUTED)
_CELL = ParagraphStyle("cell", parent=_BODY, fontSize=8, leading=10)
_TH = ParagraphStyle("th", parent=_CELL, fontName="Helvetica-Bold")
_H1 = ParagraphStyle("h1", parent=_BODY, fontName="Helvetica-Bold", fontSize=18, leading=22)
_H2 = ParagraphStyle(
    "h2",
    parent=_BODY,
    fontName="Helvetica-Bold",
    fontSize=12,
    leading=15,
    spaceBefore=12,
    keepWithNext=1,
)
_H3 = ParagraphStyle(
    "h3", parent=_BODY, fontName="Helvetica-Bold", fontSize=10, leading=13, spaceBefore=8
)
_BIG = ParagraphStyle("big", parent=_H1, fontSize=26, leading=30, textColor=_ACCENT)

_PLAIN = TableStyle(
    [
        ("LEFTPADDING", (0, 0), (-1, -1), 0),
        ("RIGHTPADDING", (0, 0), (-1, -1), 0),
        ("TOPPADDING", (0, 0), (-1, -1), 0),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 2),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
    ]
)
_GRID = TableStyle(
    [
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#f3f4f6")),
        ("GRID", (0, 0), (-1, -1), 0.4, _LINE),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("TOPPADDING", (0, 0), (-1, -1), 3),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
    ]
)
_BOX = TableStyle(
    [
        ("BOX", (0, 0), (-1, -1), 0.8, colors.HexColor("#b45309")),
        ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#fffbeb")),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
    ]
)


_ASCII = str.maketrans(
    {
        "\u2212": "-", "\u2013": "-", "\u2014": "-", "\u2192": "->", "\u2190": "<-",
        "\u2191": "up", "\u2193": "down", "\u2265": ">=", "\u2264": "<=", "\u2248": "~",
        "\u2018": "'", "\u2019": "'", "\u201c": '"', "\u201d": '"', "\u2026": "...",
    }
)  # fmt: skip


def _t(text: object) -> str:
    """Escape for Paragraph markup; Latin-1 only (built-in font), anything else becomes '?'."""
    s = ("" if text is None else str(text)).translate(_ASCII)
    return escape(s.encode("latin-1", "replace").decode("latin-1"))


def _p(text: object, style: ParagraphStyle = _BODY) -> Paragraph:
    return Paragraph(_t(text), style)


def _day(d: date | datetime) -> str:
    return f"{d.day} {d.strftime('%b %Y')}"


def _image_path(url: str, run_id: str) -> Path | None:
    """The layer file behind a block image url, or None if the url or file is not usable."""
    m = _URL_RE.search(url)
    if not m:
        return None
    try:
        path = layer_path(run_id, m.group(1), m.group(2))
    except ValueError:
        return None
    root = (earth_settings.data_dir() / "layers" / run_id).resolve()
    resolved = path.resolve()
    if not resolved.is_relative_to(root) or not resolved.is_file():
        return None
    return resolved


def _placeholder(width: float, height: float, text: str = "Image not available") -> Drawing:
    d = Drawing(width, height)
    d.add(Rect(0, 0, width, height, fillColor=colors.HexColor("#f3f4f6"), strokeColor=_LINE))
    d.add(
        String(width / 2, height / 2 - 3, text, textAnchor="middle", fontSize=8, fillColor=_MUTED)
    )
    return d


def _picture(img: BlockImage, run_id: str, width: float) -> Flowable:
    """The image scaled to `width` (placeholder if the file is missing or unreadable)."""
    path = _image_path(img.url, run_id)
    if path is not None:
        try:
            w, h = ImageReader(str(path)).getSize()
            if w > 0 and h > 0:
                return Image(str(path), width=width, height=width * h / w)
        except Exception:  # noqa: BLE001 - a bad PNG must never break the report
            pass
    return _placeholder(width, width * 0.75)


def _labelled(img: BlockImage, run_id: str, width: float) -> Table:
    t = Table(
        [[_picture(img, run_id, width)], [_p(f"{img.label} ({img.scene})", _SMALL)]],
        colWidths=[width],
    )
    t.setStyle(_PLAIN)
    return t


def _table(header: list[str], rows: list[list[str]], widths: list[float]) -> Table:
    data = [[_p(h, _TH) for h in header]] + [[_p(c, _CELL) for c in row] for row in rows]
    t = Table(data, colWidths=widths, repeatRows=1)
    t.setStyle(_GRID)
    return t


def _kv(pairs: list[tuple[str, str]]) -> Table:
    t = Table(
        [[_p(k, _SMALL), _p(v, _CELL)] for k, v in pairs], colWidths=[30 * mm, _WIDTH - 30 * mm]
    )
    t.setStyle(_PLAIN)
    return t


def _chart(block: TimelineBlock, width: float, height: float = 150) -> Drawing:
    """A simple line chart: normal band (by month), the points joined, change marks."""
    pts = sorted(block.data, key=lambda p: p.date)
    if not pts:
        return _placeholder(width, height, "No data")
    d = Drawing(width, height)
    left, right, bottom, top = 38, 8, 22, 8
    pw, ph = width - left - right, height - bottom - top
    values = [p.value for p in pts] + [b.lo for b in block.band] + [b.hi for b in block.band]
    lo, hi = min(values), max(values)
    if hi - lo < 1e-9:
        lo, hi = lo - 1, hi + 1
    pad = (hi - lo) * 0.08
    lo, hi = lo - pad, hi + pad
    t0 = pts[0].date.toordinal()
    span = max(pts[-1].date.toordinal() - t0, 1)

    def x(day: date) -> float:
        return left + pw * (day.toordinal() - t0) / span

    def y(v: float) -> float:
        return bottom + ph * (v - lo) / (hi - lo)

    d.add(Rect(left, bottom, pw, ph, fillColor=None, strokeColor=_LINE))
    # normal band: each point's month range, spanning to the midpoints between neighbours
    band = {b.month: b for b in block.band}
    for i, p in enumerate(pts):
        b = band.get(p.date.month)
        if b is None:
            continue
        xp = x(p.date)
        xa = (x(pts[i - 1].date) + xp) / 2 if i else left
        xb = (x(pts[i + 1].date) + xp) / 2 if i + 1 < len(pts) else left + pw
        d.add(
            Rect(
                xa,
                y(b.lo),
                max(xb - xa, 0.5),
                max(y(b.hi) - y(b.lo), 0.5),
                fillColor=colors.HexColor("#d1fae5"),
                strokeColor=None,
            )
        )
    for tick in range(5):  # y axis labels
        v = lo + (hi - lo) * tick / 4
        d.add(Line(left - 3, y(v), left, y(v), strokeColor=_MUTED, strokeWidth=0.5))
        d.add(
            String(left - 5, y(v) - 3, f"{v:.2f}", textAnchor="end", fontSize=7, fillColor=_MUTED)
        )
    d.add(String(left, 8, _day(pts[0].date), fontSize=7, fillColor=_MUTED))
    d.add(String(left + pw, 8, _day(pts[-1].date), textAnchor="end", fontSize=7, fillColor=_MUTED))
    for m in block.marks:
        if pts[0].date <= m.date <= pts[-1].date:
            d.add(
                Line(
                    x(m.date),
                    bottom,
                    x(m.date),
                    bottom + ph,
                    strokeColor=_RED,
                    strokeWidth=0.8,
                    strokeDashArray=[3, 2],
                )
            )
            d.add(String(x(m.date) + 2, bottom + ph - 9, _t(m.label), fontSize=7, fillColor=_RED))
    if len(pts) > 1:
        d.add(
            PolyLine(
                [c for p in pts for c in (x(p.date), y(p.value))],
                strokeColor=_ACCENT,
                strokeWidth=1.2,
            )
        )
    for p in pts:
        d.add(Circle(x(p.date), y(p.value), 1.8, fillColor=_ACCENT, strokeColor=None))
    return d


def _block(block: Any, run_id: str) -> list[Flowable]:
    """The flowables for one block, kept together on a page where they fit."""
    out: list[Flowable] = [_p(block.title, _H3)]
    if isinstance(block, ThenNowBlock):
        w = (_WIDTH - 6 * mm) / 2
        t = Table(
            [[_labelled(block.before, run_id, w), _labelled(block.after, run_id, w)]],
            colWidths=[w + 3 * mm, w + 3 * mm],
        )
        t.setStyle(_PLAIN)
        out.append(t)
    elif isinstance(block, TimelineBlock):
        out.append(_chart(block, _WIDTH))
        unit = f" ({block.unit})" if block.unit else ""
        out.append(
            _p(
                f"{block.measure}{unit}; green band = normal range for the month, "
                "dashed lines = detected change.",
                _SMALL,
            )
        )
    elif isinstance(block, HighlightBlock):
        if block.base is not None:
            out.append(_labelled(block.base, run_id, _WIDTH * 0.6))
        out.append(_p(f"Highlighted: {block.total_ha:.1f} ha in {len(block.patches)} patch(es)."))
    elif isinstance(block, StatBlock):
        out.append(_p(f"{block.value:g} {block.unit}", _BIG))
        if block.lo is not None and block.hi is not None:
            out.append(_p(f"range {block.lo:g} - {block.hi:g} {block.unit}", _SMALL))
        out.append(_p(block.label))
    elif isinstance(block, HypothesesBlock):
        rows = [
            [
                r.label,
                "; ".join(f"{k}: {v}" for k, v in r.expected.items()),
                "; ".join(f"{k}: {v}" for k, v in r.observed.items()),
                r.verdict + (f" ({r.reason})" if r.reason else ""),
            ]
            for r in block.rows
        ]
        widths = [_WIDTH * f for f in (0.22, 0.30, 0.28, 0.20)]
        out.append(_table(["Hypothesis", "Expected", "Observed", "Verdict"], rows, widths))
        if block.post_hoc:
            out.append(_p("Registered after the data was read (post hoc).", _SMALL))
    elif isinstance(block, SceneStripBlock):
        rows = [
            [
                _day(s.date),
                s.satellite,
                f"{s.cloud * 100:.0f}%",
                "yes" if s.used else "no" + (f" - {s.why}" if s.why else ""),
            ]
            for s in block.scenes
        ]
        widths = [_WIDTH * f for f in (0.2, 0.25, 0.15, 0.4)]
        out.append(_table(["Date", "Satellite", "Cloud", "Used"], rows, widths))
    elif isinstance(block, LimitsBlock):
        lines = [f"<b>What this can't tell:</b> {_t(block.cant_tell)}"]
        if block.actions:
            lines.append("<b>Instead:</b> " + _t("; ".join(a.label for a in block.actions)))
        if block.contacts:
            lines.append("<b>Contact:</b> " + _t("; ".join(block.contacts)))
        t = Table([[Paragraph("<br/>".join(lines), _BODY)]], colWidths=[_WIDTH])
        t.setStyle(_BOX)
        out.append(t)
    if block.caption:
        out.append(_p(block.caption, _SMALL))
    return [KeepTogether(out)]


def _footer(canvas: Any, doc: Any) -> None:
    canvas.saveState()
    canvas.setFont("Helvetica", 7.5)
    canvas.setFillColor(_MUTED)
    canvas.drawString(20 * mm, 10 * mm, FOOTER)
    canvas.drawRightString(A4[0] - 20 * mm, 10 * mm, f"Page {doc.page}")
    canvas.restoreState()


def render_report(run: SharedRun, run_id: str) -> bytes:
    """The PDF for a run snapshot. `run_id` only locates layer PNGs; it is never printed."""
    story: list[Flowable] = [_p(run.question, _H1), Spacer(1, 3)]
    meta = [
        run.area.name if run.area and run.area.name else None,
        f"{run.area.area_ha:.1f} ha" if run.area else None,
        _day(run.created_at),
    ]
    story.append(_p(" | ".join(m for m in meta if m), _SMALL))

    a = run.answer
    if a is None:
        story.append(_p("This run has no answer."))
    else:
        c = a.confidence
        story += [_p(a.title, _H2), _p(a.sentence), Spacer(1, 4)]
        story.append(_p(f"Confidence: {c.level} ({c.pct}%) - {c.note}"))
        if a.cause:
            story.append(_p(f"{a.l1}: {a.cause}"))
        if a.todo:
            story += [Spacer(1, 4), _p(f"{a.l2}: {a.todo}")]
        if a.stats:
            story += [
                Spacer(1, 4),
                _kv([(s.l, s.v + (f" ({s.ci})" if s.ci else "")) for s in a.stats]),
            ]
        if a.caveats:
            story.append(_p("Caveats", _H3))
            story += [_p(f"- {cav}") for cav in a.caveats]

    if run.blocks:
        story.append(_p("Evidence", _H2))
        for b in run.blocks:
            story += _block(b, run_id)

    if run.provenance:
        story.append(_p("Provenance", _H2))
        rows = [
            [
                p.satellite,
                p.scene,
                _day(p.date),
                f"{p.cloud_over_area * 100:.0f}%",
                f"{p.resolution_m:g} m",
                p.method,
            ]
            for p in run.provenance
        ]
        widths = [_WIDTH * f for f in (0.13, 0.22, 0.11, 0.07, 0.08, 0.39)]
        story.append(
            _table(["Satellite", "Scene", "Date", "Cloud", "Res.", "Method"], rows, widths)
        )

    m = run.method
    if m.cards or m.skill:
        story.append(_p("Method", _H2))
        if m.cards:
            cards = ", ".join(f"{c.id} v{c.version} ({c.status})" for c in m.cards)
            story.append(_p(f"Knowledge cards: {cards}"))
        if m.skill:
            story.append(_p(f"Skill: {m.skill.id} v{m.skill.version}"))
    if run.lang.lower().startswith(("zh", "yue")):
        story += [
            Spacer(1, 6),
            _p("Chinese text cannot be shown in this PDF; it appears as ?.", _SMALL),
        ]

    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf,
        pagesize=A4,
        leftMargin=20 * mm,
        rightMargin=20 * mm,
        topMargin=18 * mm,
        bottomMargin=20 * mm,
        title="Constellation report",
        author="Constellation",
        pageCompression=PAGE_COMPRESSION,
    )
    doc.build(story, onFirstPage=_footer, onLaterPages=_footer)
    return buf.getvalue()
